import { useEffect, useMemo, useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { loadSimulationSnapshot } from './simulationBridge';

const approaches = [
  { name: 'Northbound', count: 128, wait: '38 s', queue: 'Moderate', color: '#26735f' },
  { name: 'Southbound', count: 104, wait: '29 s', queue: 'Light', color: '#3d76b8' },
  { name: 'Brudger', count: 86, wait: '42 s', queue: 'Moderate', color: '#be7b22' },
  { name: 'Estanislao', count: 72, wait: '21 s', queue: 'Light', color: '#7b61a8' },
  { name: 'City Hall', count: 54, wait: '35 s', queue: 'Light', color: '#a24c5e' },
];
const trend = [
  { time: '07:00', volume: 220, wait: 19, queue: 7, throughput: 196 }, { time: '07:15', volume: 298, wait: 25, queue: 12, throughput: 255 },
  { time: '07:30', volume: 352, wait: 31, queue: 16, throughput: 297 }, { time: '07:45', volume: 404, wait: 39, queue: 21, throughput: 348 },
  { time: '08:00', volume: 444, wait: 33, queue: 17, throughput: 401 }, { time: '08:15', volume: 418, wait: 28, queue: 13, throughput: 390 },
];
const nav = [['overview', 'Overview'], ['analytics', 'Traffic analytics'], ['operations', 'Signal operations'], ['maintenance', 'Maintenance'], ['activity', 'Activity & logs']];
const Icon = ({ children }) => <span className="icon" aria-hidden="true">{children}</span>;
const Badge = ({ tone = 'neutral', children }) => <span className={`badge ${tone}`}>{children}</span>;
const Card = ({ children, className = '' }) => <section className={`card ${className}`}>{children}</section>;

function MiniIntersection({ phase = 'Northbound' }) {
  return <div className="intersection" role="img" aria-label={`Schematic intersection with ${phase} active`}>
    <div className="road vertical"/><div className="road horizontal"/><div className="center"/>
    {['Northbound', 'Southbound', 'Brudger', 'Estanislao', 'City Hall'].map((name, index) => <span key={name} className={`light light-${index} ${name === phase ? 'active' : ''}`}>{name === phase ? '●' : '○'}</span>)}
    <span className="schematic-note">Schematic · illustrative only</span>
  </div>;
}
function Metric({ label, value, note, tone }) { return <Card className="metric"><p>{label}</p><strong className={tone || ''}>{value}</strong><small>{note}</small></Card>; }
function Chart({ dataKey, color, title, unit }) { return <Card className="chart"><div className="card-head"><div><h3>{title}</h3><p>Example data · 15-minute windows</p></div><Badge>Illustrative</Badge></div><ResponsiveContainer width="100%" height={220}><AreaChart data={trend}><defs><linearGradient id={`${dataKey}-fill`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={color} stopOpacity=".27"/><stop offset="100%" stopColor={color} stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e4e9e6"/><XAxis dataKey="time" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false} unit={unit}/><Tooltip/><Area type="monotone" dataKey={dataKey} stroke={color} strokeWidth={2.5} fill={`url(#${dataKey}-fill)`}/></AreaChart></ResponsiveContainer></Card>; }

export default function App() {
  const [page, setPage] = useState('overview');
  const [source, setSource] = useState('example');
  const [snapshot, setSnapshot] = useState(null);
  const [sourceError, setSourceError] = useState('');
  const [notice, setNotice] = useState('');
  const [mobileNav, setMobileNav] = useState(false);
  const [settings, setSettings] = useState({ profile: 'Balanced daytime', min: 10, max: 60, yellow: 10, allRed: 3, pedestrian: 30, mode: 'Automatic' });
  useEffect(() => { if (source !== 'sumo') return undefined; let alive = true; const controller = new AbortController(); const poll = async () => { try { const next = await loadSimulationSnapshot(controller.signal); if (alive) { setSnapshot(next); setSourceError(''); } } catch { if (alive) { setSnapshot(null); setSourceError('Local SUMO bridge unavailable — showing example data.'); } } }; poll(); const id = setInterval(poll, 3000); return () => { alive = false; controller.abort(); clearInterval(id); }; }, [source]);
  const rows = useMemo(() => snapshot ? approaches.map((row) => ({ ...row, count: snapshot.approaches?.find((item) => item.name === row.name)?.observedVehicles ?? row.count })) : approaches, [snapshot]);
  const total = rows.reduce((sum, row) => sum + row.count, 0);
  const phase = snapshot?.controllerDecision?.phase || 'Northbound';
  const set = (key, value) => setSettings((current) => ({ ...current, [key]: value }));
  const log = (type, title, description) => <div className="log-row"><Badge tone={type}>{type}</Badge><div><strong>{title}</strong><p>{description}</p></div><time>Example</time></div>;
  const overview = <><div className="page-title"><div><p className="eyebrow">ANDAR INTERSECTION · EXAMPLE SITE</p><h1>Operator overview</h1><p>Traffic condition and controller context for one local intersection.</p></div><Badge tone={source === 'sumo' && snapshot ? 'ok' : 'warning'}>{source === 'sumo' && snapshot ? 'SUMO simulation · read-only' : 'Example data'}</Badge></div>{source === 'sumo' && <div className="source-banner">{snapshot ? <>SUMO decision {snapshot.simulation.decisionStep} · {snapshot.sourceFile} · recorded simulation data, not controller confirmation.</> : sourceError}</div>}<div className="status-band"><span><b>Condition</b><Badge tone="warning">Moderate demand</Badge></span><span><b>Active movement</b><strong>{phase} GREEN</strong></span><span><b>Controller</b><Badge tone="ok">Available</Badge></span><span><b>Health</b><strong>5 of 5 feeds</strong></span></div><div className="metric-grid"><Metric label="Observed vehicles" value={total} note="Example 08:00–08:15 window"/><Metric label="Average waiting time" value="33 s" note="Illustrative observation" tone="warning-text"/><Metric label="Queue status" value="Moderate" note="Northbound advisory"/><Metric label="Intersection utilization" value="71%" note="Example capacity estimate"/></div><div className="overview-grid"><Card className="intersection-card"><div className="card-head"><div><h3>Intersection condition</h3><p>Signal state is illustrative.</p></div><Badge tone="ok">Connected</Badge></div><MiniIntersection phase={phase}/><div className="movement"><div><small>Active phase</small><strong>{phase} GREEN</strong></div><div><small>Phase duration</small><strong>{snapshot?.controllerDecision?.greenSeconds || 35} s</strong></div><div><small>Operating mode</small><strong>Adaptive research prototype</strong></div></div></Card><Card className="alerts"><div className="card-head"><div><h3>Recent attention</h3><p>Prioritized operational context.</p></div><button className="text-button" onClick={() => setPage('activity')}>View all</button></div>{log('warning', 'High observed volume — Northbound', '128 vehicles in the example 15-minute window. This is not a measured queue length.')}{log('neutral', 'Camera feeds healthy', 'Five schematic feed placeholders are available in this frontend prototype.')}{log('ok', 'Controller status available', 'No field-controller confirmation is connected.')}</Card></div><Card><div className="card-head"><div><h3>Approach summary</h3><p>Example observations by approach.</p></div><Badge>08:00–08:15</Badge></div><div className="approach-table">{rows.map((row) => <div className="approach" key={row.name}><span className="dot" style={{ background: row.color }}/><strong>{row.name}</strong><span>{row.count} vehicles</span><span>{row.wait} avg wait</span><Badge tone={row.queue === 'Moderate' ? 'warning' : 'neutral'}>{row.queue} queue</Badge></div>)}</div></Card></>;
  const analytics = <><div className="page-title"><div><p className="eyebrow">TRAFFIC ANALYTICS</p><h1>Example performance trends</h1><p>Historical-style visuals for presentation and workflow review. They are not MTMB field measurements.</p></div><Badge>Example data</Badge></div><div className="chart-grid"><Chart dataKey="volume" color="#26735f" title="Traffic volume" unit=""/><Chart dataKey="wait" color="#be7b22" title="Waiting-time trend" unit="s"/><Chart dataKey="queue" color="#a24c5e" title="Queue-length trend" unit=""/><Chart dataKey="throughput" color="#3d76b8" title="Throughput" unit=""/></div><div className="two-col"><Card><div className="card-head"><div><h3>Distribution by approach</h3><p>Example observed share.</p></div></div><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={rows} dataKey="count" nameKey="name" innerRadius={55} outerRadius={95}>{rows.map((row) => <Cell key={row.name} fill={row.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></Card><Card><div className="card-head"><div><h3>Peak-period comparison</h3><p>Illustrative throughput comparison.</p></div></div><ResponsiveContainer width="100%" height={260}><BarChart data={trend}><CartesianGrid vertical={false} stroke="#e4e9e6"/><XAxis dataKey="time"/><YAxis/><Tooltip/><Bar dataKey="volume" fill="#26735f" radius={[4,4,0,0]}/><Bar dataKey="throughput" fill="#8cb9aa" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></Card></div></>;
  const operations = <><div className="page-title"><div><p className="eyebrow">SIGNAL OPERATIONS</p><h1>Adaptive signal controller</h1><p>Research-prototype view of selected movements and recent simulated decisions.</p></div><Badge tone="neutral">No field control</Badge></div><div className="operations-grid"><Card><MiniIntersection phase={phase}/><div className="operation-callout"><Badge tone="ok">ACTIVE</Badge><h2>{phase} GREEN</h2><p>{snapshot ? 'Recorded SUMO simulation decision' : 'Illustrative selected movement'}</p><strong>{snapshot?.controllerDecision?.greenSeconds || 35} seconds</strong></div></Card><Card><h3>Signal sequence</h3><p className="muted">Highlighted movement represents the current prototype state.</p><ol className="sequence">{['Northbound', 'Southbound', 'Brudger', 'Estanislao', 'City Hall', 'Pedestrian'].map((name, index) => <li className={name === phase ? 'current' : ''} key={name}><span>{index + 1}</span>{name}{name === phase && <Badge tone="ok">Active</Badge>}</li>)}</ol></Card><Card><h3>Recent decisions</h3>{log('simulated', 'Phase selected', `${phase} served for ${snapshot?.controllerDecision?.greenSeconds || 35} seconds.`)}{log('proposed', 'Timing profile', 'Balanced daytime profile is shown as a frontend preview.')}{log('neutral', 'Transition status', 'No physical transition acknowledgement is connected.')}</Card></div></>;
  const maintenance = <><div className="page-title"><div><p className="eyebrow">MAINTENANCE & CONFIGURATION</p><h1>Controller configuration preview</h1><p>Interface demonstration for future authorized maintenance workflows.</p></div><Badge tone="warning">Frontend demonstration</Badge></div><div className="demo-notice">Frontend demonstration only. Configuration validation and traffic-controller activation are not connected.</div><div className="maintenance-grid"><Card><h3>Timing profile</h3><label>Approved profile<select value={settings.profile} onChange={(event) => set('profile', event.target.value)}><option>Balanced daytime</option><option>Weekday peak</option><option>Night operation</option></select></label><label>Operating mode<select value={settings.mode} onChange={(event) => set('mode', event.target.value)}><option>Automatic</option><option>Manual preview</option></select></label><label className="check"><input type="checkbox"/> Emergency override concept <small>Preview only</small></label></Card><Card><h3>Timing guardrails</h3><div className="form-grid">{[['min','Minimum green (s)'],['max','Maximum green (s)'],['yellow','Yellow interval (s)'],['allRed','All-red clearance (s)'],['pedestrian','Pedestrian duration (s)']].map(([key,label]) => <label key={key}>{label}<input type="number" min="0" value={settings[key]} onChange={(event) => set(key, event.target.value)}/></label>)}</div><label>Safety buffer<select><option>Standard — illustrative</option><option>Enhanced — illustrative</option></select></label></Card><Card><h3>Logging & component status</h3><label className="check"><input type="checkbox" defaultChecked/> Record configuration previews</label><label className="check"><input type="checkbox" defaultChecked/> Show data-source availability in log</label><div className="component-status"><span>Dashboard frontend <Badge tone="ok">Available</Badge></span><span>Local SUMO bridge <Badge tone="neutral">Optional</Badge></span><span>Field controller <Badge tone="offline">Not connected</Badge></span></div><button className="primary" onClick={() => setNotice('Demonstration only — the configuration preview was not sent or applied.')}>Save preview</button>{notice && <p className="inline-notice" role="status">{notice}</p>}</Card></div></>;
  const activity = <><div className="page-title"><div><p className="eyebrow">ACTIVITY & SYSTEM LOGS</p><h1>Operational record</h1><p>All entries below are proposed, simulated, or frontend example events.</p></div><Badge>Example data</Badge></div><Card className="log-card"><div className="legend"><Badge tone="simulated">Simulated</Badge><Badge tone="proposed">Proposed</Badge><Badge tone="neutral">System</Badge><Badge tone="offline">Physical confirmation unavailable</Badge></div>{log('simulated', 'Signal decision recorded', `${phase} selected in the ${source === 'sumo' ? 'local SUMO' : 'example'} data context.`)}{log('warning', 'Volume advisory raised', 'Northbound reached the illustrative advisory threshold. No field alarm was sent.')}{log('proposed', 'Configuration preview available', 'Maintenance controls demonstrate a future authorized workflow only.')}{log('neutral', 'Data source ready', source === 'sumo' && snapshot ? 'Local SUMO simulation data is read-only.' : 'Example dataset is active.')}{log('offline', 'Physical controller confirmation', 'No controller, camera, sensor, or authentication service is connected.')}</Card></>;
  const pages = { overview, analytics, operations, maintenance, activity };
  return <div className="app"><a className="skip" href="#content">Skip to content</a><header><button className="brand" onClick={() => setPage('overview')}><span>AN</span><b>ANDAR</b></button><p>Traffic management research prototype</p><div className="header-controls"><label>Data source<select value={source} onChange={(event) => setSource(event.target.value)}><option value="example">Example data</option><option value="sumo">Local SUMO simulation</option></select></label><Badge tone={source === 'sumo' && snapshot ? 'ok' : 'neutral'}>{source === 'sumo' && snapshot ? 'Read-only connected' : 'Prototype'}</Badge><button className="menu" onClick={() => setMobileNav(!mobileNav)} aria-expanded={mobileNav}>Menu</button></div></header><div className="shell"><aside className={mobileNav ? 'open' : ''}><p className="nav-title">OPERATOR WORKSPACE</p>{nav.map(([id,label]) => <button className={page === id ? 'selected' : ''} onClick={() => { setPage(id); setMobileNav(false); }} key={id}><Icon>{id === 'overview' ? '▦' : id === 'analytics' ? '⌁' : id === 'operations' ? '◉' : id === 'maintenance' ? '⚙' : '≡'}</Icon>{label}</button>)}<div className="side-note"><Badge>Example data</Badge><p>Camera tiles and detections are schematic placeholders.</p></div></aside><main id="content">{pages[page]}</main></div></div>;
}
